language: haskell

notifications:
  email: false

install:
  cabal install --only-dependencies --enable-tests --enable-benchmarks --force-reinstalls

script:
  cabal configure --enable-tests --enable-benchmark -f testing && cabal build && cabal test
